import React, { useState, useEffect, useRef } from 'react';
import { useNavigate, useParams, useLocation } from 'react-router-dom';
import { toast } from 'react-hot-toast';
import artistService, { Artist } from '../../services/artistService';
import songService, { Song } from '../../services/songService';
import uploadService from '../../services/uploadService';
import videoService, { VideoFormData } from '../../services/videoService';
import {
  ArrowLeft, Upload, Save, Loader2, Check, ChevronDown,
  Video as VideoIcon, Image as ImageIcon, RefreshCw, CheckCircle2, X, Sparkles,
} from 'lucide-react';
import Preloader from '../../components/ui/Preloader';

// Grabs a frame partway into the clip and returns it as a JPEG File, so a
// thumbnail always exists without forcing the admin to pick one manually.
function generateThumbnailFromVideo(file: File): Promise<File> {
  return new Promise((resolve, reject) => {
    const video = document.createElement('video');
    video.preload = 'metadata';
    video.muted = true;
    video.playsInline = true;
    const url = URL.createObjectURL(file);
    video.src = url;

    const cleanup = () => URL.revokeObjectURL(url);
    const timeout = setTimeout(() => { cleanup(); reject(new Error('Timed out reading video')); }, 15000);

    video.onloadedmetadata = () => {
      video.currentTime = Math.min(1, (video.duration || 2) / 10);
    };

    video.onseeked = () => {
      clearTimeout(timeout);
      const canvas = document.createElement('canvas');
      canvas.width = video.videoWidth || 640;
      canvas.height = video.videoHeight || 360;
      const ctx = canvas.getContext('2d');
      if (!ctx) { cleanup(); reject(new Error('Canvas not supported')); return; }
      ctx.drawImage(video, 0, 0, canvas.width, canvas.height);
      canvas.toBlob((blob) => {
        cleanup();
        if (!blob) { reject(new Error('Failed to generate thumbnail')); return; }
        resolve(new File([blob], `${file.name.replace(/\.[^.]+$/, '')}-thumb.jpg`, { type: 'image/jpeg' }));
      }, 'image/jpeg', 0.85);
    };

    video.onerror = () => { clearTimeout(timeout); cleanup(); reject(new Error('Failed to load video')); };
  });
}

const VideoForm: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const location = useLocation();
  const fromStream = (location.state as { fromStream?: VideoFormData } | null)?.fromStream;
  const isEditing = !!id;

  const [loading, setLoading] = useState<boolean>(isEditing);
  const [artists, setArtists] = useState<Artist[]>([]);
  const [songs, setSongs] = useState<Song[]>([]);

  const [formData, setFormData] = useState<VideoFormData>(fromStream || {
    title: '',
    description: '',
    videoUrl: '',
    thumbnailUrl: '',
    artistId: '',
    songId: '',
    pushedToFeed: false,
  });

  const [videoFile, setVideoFile] = useState<File | null>(null);
  const [thumbnailFile, setThumbnailFile] = useState<File | null>(null);
  const [thumbnailPreview, setThumbnailPreview] = useState<string | null>(fromStream?.thumbnailUrl || null);
  const [thumbnailAutoGenerated, setThumbnailAutoGenerated] = useState(false);
  const [generatingThumbnail, setGeneratingThumbnail] = useState(false);
  const [videoProgress, setVideoProgress] = useState<number>(0);
  const [thumbnailProgress, setThumbnailProgress] = useState<number>(0);
  const [uploading, setUploading] = useState<boolean>(false);

  const videoInputRef = useRef<HTMLInputElement>(null);
  const thumbInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    (async () => {
      try {
        const [aData, sData] = await Promise.all([
          artistService.getAllArtists(),
          songService.getAllSongs(),
        ]);
        setArtists(aData);
        setSongs(sData);

        if (id) {
          const v = await videoService.getVideoById(id);
          setFormData({
            title: v.title,
            description: v.description || '',
            videoUrl: v.videoUrl,
            thumbnailUrl: v.thumbnailUrl || '',
            artistId: v.artist?._id || '',
            songId: v.song?._id || '',
            pushedToFeed: v.pushedToFeed,
          });
          if (v.thumbnailUrl) setThumbnailPreview(v.thumbnailUrl);
        }
      } catch {
        toast.error('Failed to load video details');
      } finally {
        setLoading(false);
      }
    })();
  }, [id]);

  const filteredSongs = songs.filter(s => {
    const artistId = typeof s.artist === 'string' ? s.artist : s.artist?._id;
    return artistId === formData.artistId;
  });

  const handleVideoFileChange = async (file: File | null) => {
    setVideoFile(file);
    if (!file) return;

    setGeneratingThumbnail(true);
    try {
      const generated = await generateThumbnailFromVideo(file);
      setThumbnailFile(generated);
      setThumbnailAutoGenerated(true);
      setThumbnailPreview(URL.createObjectURL(generated));
    } catch {
      // Non-fatal — admin can still pick a thumbnail manually
      toast.error('Could not auto-generate a thumbnail from this video. Please select one manually.');
    } finally {
      setGeneratingThumbnail(false);
    }
  };

  const handleThumbnailFileChange = (file: File | null) => {
    setThumbnailFile(file);
    setThumbnailAutoGenerated(false);
    if (file) setThumbnailPreview(URL.createObjectURL(file));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setUploading(true);
    const loadingId = toast.loading('Saving video...');

    try {
      let finalVideoUrl = formData.videoUrl;
      let finalThumbnailUrl = formData.thumbnailUrl;

      if (videoFile) {
        const presign = await uploadService.getPresignedVideoUrl(videoFile.name, videoFile.type);
        await uploadService.uploadToS3(presign.uploadUrl, videoFile, setVideoProgress);
        finalVideoUrl = presign.publicUrl;
      } else if (!isEditing && !formData.videoUrl) {
        toast.error('Video file is required', { id: loadingId });
        setUploading(false);
        return;
      }

      if (thumbnailFile) {
        const presign = await uploadService.getPresignedThumbnailUrl(thumbnailFile.name, thumbnailFile.type);
        await uploadService.uploadToS3(presign.uploadUrl, thumbnailFile, setThumbnailProgress);
        finalThumbnailUrl = presign.publicUrl;
      }

      const videoPayload = { ...formData, videoUrl: finalVideoUrl, thumbnailUrl: finalThumbnailUrl };

      if (isEditing && id) {
        await videoService.updateVideo(id, videoPayload);
        toast.success('Video updated successfully', { id: loadingId });
      } else {
        await videoService.createVideo(videoPayload);
        toast.success('Video uploaded successfully', { id: loadingId });
      }
      navigate('/admin/video-management');
    } catch (err: any) {
      toast.error(err.response?.data?.message || err.message || 'Save failed', { id: loadingId });
    } finally {
      setUploading(false);
    }
  };

  if (loading) return <Preloader isVisible text="Loading video details..." />;

  return (
    <div className="space-y-10 pb-24 max-w-3xl">
      <div className="flex items-center gap-5">
        <button
          type="button"
          onClick={() => navigate('/admin/video-management')}
          className="w-14 h-14 rounded-2xl flex items-center justify-center bg-zinc-50 dark:bg-zinc-950 border border-black/5 dark:border-white/5 text-zinc-600 hover:text-zinc-900 dark:text-white transition-all shadow-inner group"
        >
          <ArrowLeft size={22} className="group-hover:-translate-x-1 transition-transform" />
        </button>
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-zinc-900 dark:text-white leading-none">
            {isEditing ? 'Edit Video' : 'Upload Video'}
          </h1>
          <p className="text-zinc-500 text-xs font-semibold mt-1">Video Catalog Form</p>
        </div>
      </div>

      <form onSubmit={handleSubmit} className="premium-card p-10 space-y-10 bg-white dark:bg-[#0a0a0a]">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-10">
          <div className="space-y-4">
            <label className="text-[10px] font-bold text-zinc-500 uppercase tracking-widest ml-1">Video Title <span className="text-emerald-500">*</span></label>
            <input
              required className="w-full h-16 px-8 bg-zinc-50 dark:bg-zinc-950 border border-black/5 dark:border-white/5 rounded-2xl text-zinc-900 dark:text-white text-[11px] font-bold tracking-wide uppercase focus:outline-none focus:border-emerald-500/30 transition-all shadow-inner placeholder:text-zinc-800"
              placeholder="Enter video title"
              value={formData.title}
              onChange={e => setFormData({ ...formData, title: e.target.value })}
            />
          </div>
          <div className="space-y-4">
            <label className="text-[10px] font-bold text-zinc-500 uppercase tracking-widest ml-1">Artist</label>
            <div className="relative group/sel">
              <select
                required className="w-full h-16 px-8 bg-zinc-50 dark:bg-zinc-950 border border-black/5 dark:border-white/5 rounded-2xl text-zinc-900 dark:text-white text-[11px] font-bold tracking-wide uppercase focus:outline-none focus:border-emerald-500/30 appearance-none shadow-inner transition-all cursor-pointer"
                value={formData.artistId}
                onChange={e => setFormData({ ...formData, artistId: e.target.value, songId: '' })}
              >
                <option value="">Select Artist</option>
                {artists.map(a => (
                  <option key={a._id} value={a._id}>{a.name.toUpperCase()}</option>
                ))}
              </select>
              <ChevronDown className="absolute right-6 top-1/2 -translate-y-1/2 text-zinc-800 pointer-events-none group-focus-within/sel:rotate-180 duration-500 transition-all group-focus-within/sel:text-emerald-500" />
            </div>
          </div>
        </div>

        <div className="space-y-4">
          <label className="text-[10px] font-bold text-zinc-500 uppercase tracking-widest ml-1">Description</label>
          <textarea
            disabled={uploading} className="w-full p-8 bg-zinc-50 dark:bg-zinc-950 border border-black/5 dark:border-white/5 rounded-3xl text-zinc-700 dark:text-zinc-300 text-[11px] font-bold tracking-wide focus:outline-none focus:border-emerald-500/30 focus:ring-4 focus:ring-emerald-500/5 transition-all shadow-inner resize-none h-32 leading-relaxed placeholder:text-zinc-800"
            placeholder="Provide description for this video..."
            value={formData.description}
            onChange={e => setFormData({ ...formData, description: e.target.value })}
          />
        </div>

        {/* Video Upload Area — always visible, including when editing, so the file can be replaced */}
        <div className="space-y-4">
          <label className="text-[10px] font-bold text-zinc-500 uppercase tracking-widest ml-1">
            {formData.videoUrl ? 'Replace Video File (optional)' : 'Upload Video File'}
          </label>
          {formData.videoUrl && !videoFile && (
            <div className="flex items-center gap-4 p-4 bg-zinc-50 dark:bg-zinc-950 border border-black/5 dark:border-white/5 rounded-2xl">
              <video src={formData.videoUrl} className="w-24 h-16 object-cover rounded-xl bg-black" muted />
              <div className="min-w-0">
                <p className="text-[10px] font-bold text-zinc-900 dark:text-white uppercase tracking-widest">{isEditing ? 'Current Video' : 'Source Recording'}</p>
                <p className="text-[9px] text-zinc-600 truncate">{formData.videoUrl}</p>
              </div>
            </div>
          )}
          <div
            onClick={() => !uploading && videoInputRef.current?.click()}
            className={`border-2 border-dashed rounded-[2.5rem] p-12 flex flex-col items-center justify-center transition-all cursor-pointer relative overflow-hidden ${videoFile ? 'border-emerald-500 bg-emerald-500/5 shadow-[0_0_30px_rgba(16,185,129,0.1)]' : 'border-white/5 hover:border-emerald-500/20 bg-zinc-950 shadow-inner'} ${uploading ? 'opacity-50 cursor-not-allowed' : ''} group/up`}
          >
            <input
              type="file" ref={videoInputRef} className="hidden"
              accept="video/*" onChange={(e) => handleVideoFileChange(e.target.files?.[0] || null)}
            />
            {videoFile ? (
              <div className="flex items-center gap-6 relative z-10">
                <div className="w-16 h-16 bg-emerald-500/10 rounded-2xl flex items-center justify-center border border-emerald-500/20">
                  <VideoIcon className="text-emerald-500" size={32} />
                </div>
                <div className="text-left">
                  <p className="text-sm font-bold text-zinc-900 dark:text-white uppercase tracking-tight">{videoFile.name}</p>
                  <p className="text-[10px] text-zinc-600 font-bold uppercase tracking-widest mt-1">{(videoFile.size / (1024 * 1024)).toFixed(2)} MB • Ready to Upload</p>
                </div>
                {videoProgress === 100 && <CheckCircle2 className="text-emerald-500 ml-4" size={24} />}
              </div>
            ) : (
              <div className="flex flex-col items-center relative z-10">
                <div className="w-20 h-20 bg-zinc-900 rounded-[2rem] flex items-center justify-center mb-6 border border-black/5 dark:border-white/5 shadow-2xl group-hover/up:scale-110 transition-transform duration-700">
                  <Upload className="text-zinc-700 group-hover/up:text-emerald-500 transition-colors" size={32} />
                </div>
                <p className="text-[10px] font-black text-zinc-500 uppercase tracking-widest">{formData.videoUrl ? 'Select Replacement Video' : 'Select Video File'}</p>
                <p className="text-[9px] text-zinc-700 mt-3 font-bold uppercase tracking-widest opacity-60">MP4, WEBM, MOV • Max file size: 500MB</p>
              </div>
            )}
          </div>
          {videoProgress > 0 && videoProgress < 100 && (
            <div className="px-1">
              <div className="w-full bg-zinc-50 dark:bg-zinc-950 border border-black/5 dark:border-white/5 rounded-full h-2 overflow-hidden shadow-inner">
                <div style={{ width: `${videoProgress}%` }} className="bg-emerald-500 h-full shadow-[0_0_15px_#10b981] transition-all" />
              </div>
              <p className="text-[8px] font-black text-emerald-500/60 uppercase tracking-widest mt-2 text-right">Uploading: {videoProgress}%</p>
            </div>
          )}
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-10">
          <div className="space-y-4">
            <label className="text-[10px] font-bold text-zinc-500 uppercase tracking-widest ml-1">Link to Song</label>
            <div className="relative group/sel">
              <select
                disabled={uploading} className="w-full h-16 px-8 bg-zinc-50 dark:bg-zinc-950 border border-black/5 dark:border-white/5 rounded-2xl text-zinc-900 dark:text-white text-[11px] font-bold tracking-wide uppercase focus:outline-none focus:border-emerald-500/30 appearance-none shadow-inner transition-all cursor-pointer"
                value={formData.songId}
                onChange={e => setFormData({ ...formData, songId: e.target.value })}
              >
                <option value="">No Linked Song</option>
                {filteredSongs.map(s => (
                  <option key={s._id} value={s._id}>{s.name.toUpperCase()}</option>
                ))}
              </select>
              <ChevronDown className="absolute right-6 top-1/2 -translate-y-1/2 text-zinc-800 pointer-events-none group-focus-within/sel:rotate-180 duration-500 transition-all group-focus-within/sel:text-emerald-500" />
            </div>
          </div>
          <div className="space-y-4">
            <label className="text-[10px] font-bold text-zinc-500 uppercase tracking-widest ml-1 flex items-center gap-2">
              Thumbnail Image
              {thumbnailAutoGenerated && (
                <span className="inline-flex items-center gap-1 text-emerald-500 normal-case tracking-normal font-semibold">
                  <Sparkles size={10} /> Auto-generated
                </span>
              )}
            </label>
            <div
              onClick={() => !uploading && thumbInputRef.current?.click()}
              className={`h-16 px-8 border rounded-2xl flex items-center justify-between cursor-pointer transition-all ${thumbnailFile || thumbnailPreview ? 'border-emerald-500/30 bg-emerald-500/5 shadow-[0_0_20px_rgba(16,185,129,0.1)]' : 'border-white/5 bg-zinc-950 hover:border-emerald-500/20 shadow-inner'} ${uploading ? 'opacity-50' : ''} group/th`}
            >
              <input
                type="file" ref={thumbInputRef} className="hidden"
                accept="image/*" onChange={(e) => handleThumbnailFileChange(e.target.files?.[0] || null)}
              />
              <div className="flex items-center gap-4 truncate">
                {generatingThumbnail ? (
                  <>
                    <RefreshCw size={18} className="text-emerald-500 animate-spin" />
                    <span className="text-[10px] font-bold text-zinc-600 truncate uppercase tracking-widest">Generating from video...</span>
                  </>
                ) : thumbnailPreview ? (
                  <>
                    <img src={thumbnailPreview} className="w-10 h-10 rounded-xl object-cover border border-emerald-500/20" />
                    <span className="text-[10px] font-bold text-zinc-900 dark:text-white truncate uppercase tracking-widest">{thumbnailFile ? thumbnailFile.name : 'Current thumbnail'}</span>
                  </>
                ) : (
                  <>
                    <Upload size={18} className="text-zinc-700 group-hover/th:text-emerald-500 transition-colors" />
                    <span className="text-[10px] font-bold text-zinc-600 truncate uppercase tracking-widest">Select Image</span>
                  </>
                )}
              </div>
              <ImageIcon size={18} className="text-zinc-800 group-hover/th:text-zinc-600 transition-colors flex-shrink-0" />
            </div>
          </div>
        </div>

        <div className="flex items-center justify-between pt-10 border-t border-black/5 dark:border-white/5">
          <div className="flex items-center gap-6">
            <button
              type="button"
              onClick={() => setFormData({ ...formData, pushedToFeed: !formData.pushedToFeed })}
              className={`relative w-14 h-7 rounded-full transition-all duration-500 ${formData.pushedToFeed ? 'bg-emerald-500' : 'bg-zinc-800 border border-white/5'}`}
            >
              <div className={`absolute top-1 w-5 h-5 rounded-full bg-white transition-all duration-500 ${formData.pushedToFeed ? 'left-8 shadow-[0_0_15px_white]' : 'left-1'}`} />
            </button>
            <div>
              <span className="text-[10px] font-black text-zinc-900 dark:text-white uppercase tracking-[0.2em] block">Promote to Reels</span>
              <span className="text-[8px] font-bold text-zinc-700 uppercase tracking-widest block mt-1">Directly feature this video in the Reels feed</span>
            </div>
          </div>

          {uploading && (
            <div className="flex items-center gap-3 text-emerald-500">
              <RefreshCw className="h-5 w-5 animate-spin" />
              <span className="text-[9px] font-black uppercase tracking-widest">Saving...</span>
            </div>
          )}
        </div>

        <div className="flex gap-6 pt-6">
          <button
            type="button" disabled={uploading}
            onClick={() => navigate('/admin/video-management')}
            className="flex-1 h-16 bg-zinc-50 dark:bg-zinc-950 text-zinc-600 rounded-2xl text-[10px] font-bold uppercase tracking-widest border border-black/5 dark:border-white/5 hover:bg-black/5 dark:bg-white/5 transition-all"
          >
            Cancel
          </button>
          <button
            type="submit"
            disabled={uploading || generatingThumbnail || (!isEditing && !videoFile && !formData.videoUrl)}
            className="flex-1 h-16 bg-white text-black rounded-2xl text-[10px] font-bold uppercase tracking-widest shadow-2xl hover:bg-emerald-400 transition-all flex items-center justify-center gap-4 group disabled:opacity-50"
          >
            {uploading ? <Loader2 className="w-5 h-5 animate-spin" /> : <Save size={20} className="group-hover:translate-y-1 transition-transform" />}
            {isEditing ? 'Save Changes' : 'Upload Video'}
          </button>
        </div>
      </form>
    </div>
  );
};

export default VideoForm;
